export const text = {
	mutedNotifications:               'Notifications muted',
	unmutedNotifications:             'Notifications unmuted',
	notificationsStatus:              'Notifications status',
	weveSentAnEmailTo:                'We\'ve sent an email to',
	openInToActivateAccount:          'Open it up to activate your account.',
	yourEmailHasBeenActivated:        'Your email has been activated! You may now proceed to the sign in page.',
	successfullyLoggenIn:             'Successfully logged in!',
	invalidToken:                     'Invalid token',
	tokenIsExpired:                   'Token is expired',
	emailAlreadyInUse:                'Email already in use',
	success:                          'Success!',
	emailOrPasswordIsIncorrect:       'Your username/password are incorrect or account is not activated. Please try again or contact admin',
	accountIsArchived:                'Your account is archived. Please contact admin',
	facebookEmailIsPrivateOrNotExist: 'Facebook Email is private or not exist',
	failedToGetTheFacebookTokens:     'Failed to get the facebook tokens',
	failedToGetTheFacebookUsers:      'Failed to get the facebook user',
	gihubEmailIsPrivateOrNotExist:    'Github Email is private or not exist',
	failedToGetGihubTokens:           'Failed to get the github tokens',
	failedToGetGithubUser:            'Failed to get the github user',
	googleEmailIsNotVerified:         'Google Email is not Verified',
	failedToGetTheGoogleUser:         'Failed to get the google user',
	failedToGetTheGoogleTokens:       'Failed to get the google tokens',
	confiramtionCodeHasBeenSended:    'Confirmation code has been sended to the old and new email',
	oneOfProvidedCodesAreNotValid:    'One of provided codes are not valid!',
	wrongAuthProvider:                'Wrong auth provider',
	wrongPassword:                    'Wrong password',
	samePassword:                     'New password and old password are the same',
	wrongId:                          'Wrong id',
	userUsedAnotherAuthProvider:      'User using an another auth provider or not exist',
	userNotExist:                     'User not exist',
	newPasswordSameAsOld:             'New password and old password are the same',
} as const
