-- AlterTable
ALTER TABLE "B2BClients" ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL;

-- AlterTable
ALTER TABLE "EditedMaterial" ALTER COLUMN "url" SET DATA TYPE VARCHAR(400),
ALTER COLUMN "thumbnailUrl" SET DATA TYPE VARCHAR(400),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(400);
