
export enum OrderValueLevel {
	LOW = 'LOW',
	REGULAR = 'REGULAR',
	HIGH = 'HIGH',
}

export enum EngagementLevel {
	B2B_NEW = 'B2B_NEW',
	B2B_RETURNING = 'B2B_RETURNING',
	B2B_LOW_VOLUME = 'B2B_LOW_VOLUME',
	B2B_REGULAR = 'B2B_REGULAR',
	B2C_FIRST_ORDER = 'B2C_FIRST_ORDER',
	B2C_RETURNED_ORDER = 'B2C_RETURNED_ORDER',
	B2C_NOT_THE_FIRST_ORDER = 'B2C_NOT_THE_FIRST_ORDER',
}
