-- AlterTable
ALTER TABLE "EarningRate" ALTER COLUMN "earningRate" SET DEFAULT 50,
ALTER COLUMN "earningRate" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "ProductType" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;
