-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('CONTRACTOR', 'CLIENT', 'BOOKINGS');

-- CreateEnum
CREATE TYPE "NotificationUrgency" AS ENUM ('NORMAL', 'URGENT', 'VERY_URGENT');

-- CreateEnum
CREATE TYPE "NotificationCategory" AS ENUM ('CONTRACTOR_RUNNING_LATE_15_MINUTES', 'CONTRACTOR_RUNNING_LATE_5_10_MINUTES', 'CONTRACTOR_NO_AVAILABILITY_NEXT_WEEK', 'CONTRACTOR_ADDED_CERTIFICATES', 'CONTRACTOR_NO_ARRIVAL_CONFIRMATION', 'CONTRACTOR_DISPUTE_INVOICES', 'CONTRACTOR_CHANGED_RADIUS', 'CONTRACTOR_ADDED_SKILLS', 'CONTRACTOR_CHANGED_TRANSPORTATION_METHOD', 'CONTRACTOR_ADJUSTED_AVAILABILITY', 'CLIENT_B2B_ADDED_NEW_OFFICE', 'CLIENT_B2B_DELETED_OFFICE', 'CLIENT_B2B_DISPUTE_INVOICES', 'CLIENT_B2B_CHANGED_CONTACT_INFO', 'CLIENT_B2B_FIRST_ORDER', 'BOOKINGS_NEW_BOOKING', 'BOOKINGS_URGENT_REPORT_FROM_CONTRACTOR', 'BOOKINGS_REPORT_AFTER_COMPLETION', 'BOOKINGS_CHALLENGE_CONTENT_ADJUSTMENTS', 'BOOKINGS_REVIEW_LESS_THAN_3_STARS', 'BOOKINGS_CONFLICT_DUE_TO_DELAY', 'BOOKINGS_AVAILABILITY_CHANGED_DUE_TO_SICKNESS', 'BOOKINGS_LOST_B2B', 'BOOKINGS_CAPACITY_ABOVE_90_PERCENT', 'BOOKINGS_CAPACITY_ABOVE_80_PERCENT', 'BOOKINGS_ADJUSTED');

-- CreateTable
CREATE TABLE "Notification" (
    "id" UUID NOT NULL,
    "title" VARCHAR(100) NOT NULL DEFAULT '',
    "message" TEXT,
    "type" "NotificationType" NOT NULL DEFAULT 'CONTRACTOR',
    "urgency" "NotificationUrgency" NOT NULL DEFAULT 'NORMAL',
    "category" "NotificationCategory",
    "date_sent" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAdminId" UUID,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_readAdminId_fkey" FOREIGN KEY ("readAdminId") REFERENCES "admin"("id") ON DELETE SET NULL ON UPDATE CASCADE;
